<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hotel</name>
   <tag></tag>
   <elementGuidId>a41136b9-df28-44ef-9a12-0be62b2ad18c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[3]/div/div[3]/div/div/div[3]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d598c36-215a-4afc-81d4-cab15ab1d9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/hotel</value>
      <webElementGuid>621761f9-0540-4f29-a279-fe48a2e9adef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>{&quot;event&quot;:&quot;click&quot;,&quot;eventCategory&quot;:&quot;enterVertical&quot;,&quot;eventLabel&quot;:&quot;hotel&quot;}</value>
      <webElementGuid>7265127d-8d4b-4549-9d83-1c44ca95a12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotel</value>
      <webElementGuid>e81a0475-760d-4c8d-bc06-8c150c71d2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;home-page&quot;]/div[@class=&quot;left-side&quot;]/div[@class=&quot;header-v3&quot;]/div[@class=&quot;header-bottom-layer&quot;]/div[@class=&quot;header-container&quot;]/div[@class=&quot;header-left-side&quot;]/div[@class=&quot;product-list visible&quot;]/div[@class=&quot;product-link&quot;]/a[1]</value>
      <webElementGuid>8aebe34a-8ad5-4f74-bddf-85bd41b82e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[3]/div/div[3]/div/div/div[3]/div[2]/a</value>
      <webElementGuid>7b634123-d1bc-434e-9a2c-739d622160c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hotel')]</value>
      <webElementGuid>2eb5eabd-7449-4e6a-aa32-21b06c055c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiket Pesawat'])[1]/following::a[1]</value>
      <webElementGuid>5823a6a7-5714-4153-9f71-4c87afc32b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Do'])[1]/preceding::a[1]</value>
      <webElementGuid>903bdec3-639a-4049-b7ed-14fe260d89e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiket Kereta Api'])[1]/preceding::a[2]</value>
      <webElementGuid>6ffbb813-2d86-4048-9f1a-4dc587217e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotel']/parent::*</value>
      <webElementGuid>bf2adf06-8b3d-440f-b0d7-fc87a8b42bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/hotel')]</value>
      <webElementGuid>2fd40a20-5240-46ac-b7ff-fa4cfa9960d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>6c9a816a-2dc1-42e4-bd0d-c5b7b399f59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/hotel' and (text() = 'Hotel' or . = 'Hotel')]</value>
      <webElementGuid>c8a4bf85-cb63-4bc9-805c-c5acf540b106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
