<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kamar_btn-operation</name>
   <tag></tag>
   <elementGuidId>6ea2b91a-1359-4fc1-986e-1f2971cc094e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='guestAndRoom']/div/div/div/div/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>67698bc4-c81f-4a63-b518-3a2fcf6052bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-operation </value>
      <webElementGuid>ff2b0f1d-6c7a-4d95-ba77-b496592a14be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[1]/div[@class=&quot;landing-desktop&quot;]/div[@class=&quot;hero-section&quot;]/div[@class=&quot;widget-container&quot;]/div[@class=&quot;widget-hotel&quot;]/div[@class=&quot;widget-section&quot;]/div[@class=&quot;widget-section-item section-right&quot;]/div[@class=&quot;widget-input&quot;]/div[@id=&quot;guestAndRoom&quot;]/div[@class=&quot;widget-popup  widget-guest-room-input&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;popup-content&quot;]/div[@class=&quot;guest-room-popup-container&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;number-input&quot;]/div[@class=&quot;btn-operation&quot;]</value>
      <webElementGuid>f2ee5b66-22a7-4c80-bedc-fc3a809f2be5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guestAndRoom']/div/div/div/div/div/div[2]/div[3]</value>
      <webElementGuid>449556ca-0c8d-42d1-a72d-4215012f8a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamar'])[1]/following::div[4]</value>
      <webElementGuid>4504398c-0df7-4e5c-a9b9-9deb52af27f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamar &amp; Tamu'])[1]/following::div[12]</value>
      <webElementGuid>629e7469-39e4-489d-a8ae-366faa4c4253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tamu'])[1]/preceding::div[1]</value>
      <webElementGuid>c0365640-7d49-4c96-8381-d4a72ec0c57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak (dibawah 17 tahun)'])[1]/preceding::div[7]</value>
      <webElementGuid>73a3a60e-f2bb-4ac3-81de-146c91c8a230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div[3]</value>
      <webElementGuid>82f482f4-a1ec-48d4-b3bd-fe9b73213a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
