<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Anak 1_tix tixicon tixicon-down icon</name>
   <tag></tag>
   <elementGuidId>d5ea2736-6b35-4c27-8baf-2e39d578c5c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.tix.tixicon.tixicon-down.icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='guestAndRoom']/div/div/div/div/div[4]/div[2]/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7489095f-95ad-4593-81c1-3fbb18cfa910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tix tixicon tixicon-down icon</value>
      <webElementGuid>0829fd4d-f331-49a7-be48-e546a4848e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[1]/div[@class=&quot;landing-desktop&quot;]/div[@class=&quot;hero-section&quot;]/div[@class=&quot;widget-container&quot;]/div[@class=&quot;widget-hotel&quot;]/div[@class=&quot;widget-section&quot;]/div[@class=&quot;widget-section-item section-right&quot;]/div[@class=&quot;widget-input&quot;]/div[@id=&quot;guestAndRoom&quot;]/div[@class=&quot;widget-popup  widget-guest-room-input&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;popup-content&quot;]/div[@class=&quot;guest-room-popup-container&quot;]/div[@class=&quot;children-rate&quot;]/div[@class=&quot;children-rate-list&quot;]/div[@class=&quot;children-dropdown-select-wrapper&quot;]/div[@class=&quot;children-dropdown-select&quot;]/div[@class=&quot;children-dropdown-select__trigger&quot;]/i[@class=&quot;tix tixicon tixicon-down icon&quot;]</value>
      <webElementGuid>d405810f-5932-4789-9091-23c33a028ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guestAndRoom']/div/div/div/div/div[4]/div[2]/div/div/div/i</value>
      <webElementGuid>f5463ed4-2fe1-4961-a05c-c4680bf0c8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/i</value>
      <webElementGuid>fd646d5e-80c1-40a1-b429-63c7a1554ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
