<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tujuan_destination</name>
   <tag></tag>
   <elementGuidId>202f873e-ed57-4e76-9362-eeeb83de51a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#destination-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='destination-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>322fd723-f692-4a47-99d2-4f70f9ffc423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>destination-input</value>
      <webElementGuid>268289b5-3b5a-47bb-b711-efaab1932203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mau nginep ke mana?</value>
      <webElementGuid>cac0667a-9354-4215-9055-e4560e39df72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>694ef0bb-0639-4e87-8e8c-26e45cf89c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e9b16add-ccd0-40d3-80eb-943dbc2492a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>destination-input input </value>
      <webElementGuid>98fd05dd-65b9-42c4-a939-c68453c2392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[1]/div[@class=&quot;landing-desktop&quot;]/div[@class=&quot;hero-section&quot;]/div[@class=&quot;widget-container&quot;]/div[@class=&quot;widget-hotel&quot;]/div[@class=&quot;widget-section&quot;]/div[@class=&quot;widget-section-item section-left&quot;]/div[@class=&quot;widget-input&quot;]/div[@class=&quot;input-container&quot;]/input[@id=&quot;destination-input&quot;]</value>
      <webElementGuid>a6ed3d72-6b75-4e07-bbd7-f1b960aea669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='destination-input']</value>
      <webElementGuid>125c93a2-a6a5-44c0-822d-2f68d2cc3594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>675a60b4-6865-4204-acba-9352ba78db30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>31cead2d-093c-4814-a525-9e6380dd4023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'destination-input' and @placeholder = 'Mau nginep ke mana?' and @name = 'destination']</value>
      <webElementGuid>bf9a8a99-3eca-46fc-9676-07aac0301015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
